spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/microservice1/**
          filters:
            - RoleValidationFilter
        - id: swagger-ui
          uri: lb://PRODUCT-SERVICE 
          predicates:
            - Path=/openapi/**
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/microservice2/**
    loadbalancer:
      ribbon:
        enabled: false

logging:
  level:
    org.springframework.cloud.sleuth: DEBUG # Optional, for verbose tracing info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  metrics:
    tracing:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
        
server:
  port: 8086

role-validation:
  enabled: false
  required-role: microservice1
  client-name: myclient

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
