spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
          filters:
            - RoleValidationFilter=ROLE_PRODUCT,product-service
        - id: swagger-ui
          uri: lb://PRODUCT-SERVICE 
          predicates:
            - Path=/openapi/**
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
          filters:
            - RoleValidationFilter=ROLE_CUSTOMER,customer-service
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/api/reviews/**
          filters:
            - RoleValidationFilter=ROLE_REVIEW,review-service

    loadbalancer:
      ribbon:
        enabled: false

logging:
  level:
    org.springframework.cloud.sleuth: DEBUG # Optional, for verbose tracing info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  metrics:
    tracing:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
        
server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
