spring:
  application:
    name: customer-service
    
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: schema2
    locations: classpath:db/migration
    
  datasource:
    url: jdbc:postgresql://localhost:5432/shared_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          default_schema: schema2
          dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

microservice1:
  hello-url: lb://PRODUCT-SERVICE/microservice1/hello
  grpc-server: localhost:9090

logging:
  level:
    org.springframework.cloud.sleuth: DEBUG # Optional, for verbose tracing info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  metrics:
    tracing:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
