spring:
  application:
    name: microservice2
    
  datasource:
    url: jdbc:h2:mem:microservice2db
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        connection:
          autocommit: false
        format_sql: true

server:
  port: 8081

microservice1:
  hello-url: lb://MICROSERVICE1/microservice1/hello
  grpc-server: localhost:9090

logging:
  level:
    org.springframework.cloud.sleuth: DEBUG # Optional, for verbose tracing info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  influx:
    metrics:
      export:
        enabled: true
        bucket: micrometer
        uri: http://localhost:8686
        org: my-org
        token: k7Ab54m-sZMJaNXrQGJrjnGonk-FOEgAVWhTmA3w6uAwj-Pt0YD_XNuO0MqpqOJPobl3N_od_dm-66pucbPIAg==
        step: 10s
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
